version: "3.9"

services:
    ### Laravel #########################################
    laravel:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: ${APP_BUILD_TARGET:-development}
        environment:
            - TZ=UTC
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./.env.example:/var/www/html/.env
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network

    ### Postgres #########################################
    postgres:
        image: postgres:latest
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
            interval: 5s
            timeout: 30s
            retries: 6
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "pass"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

volumes:
    postgres-data:
networks:
    app-network:
